/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.8.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the KnowledgePageSearchResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KnowledgePageSearchResponse{}

// KnowledgePageSearchResponse Ranked knowledge-page search results (BM25 + vector, RRF-fused).
type KnowledgePageSearchResponse struct {
	Results []KnowledgePageSearchResult `json:"results"`
	Total int32 `json:"total"`
}

type _KnowledgePageSearchResponse KnowledgePageSearchResponse

// NewKnowledgePageSearchResponse instantiates a new KnowledgePageSearchResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKnowledgePageSearchResponse(results []KnowledgePageSearchResult, total int32) *KnowledgePageSearchResponse {
	this := KnowledgePageSearchResponse{}
	this.Results = results
	this.Total = total
	return &this
}

// NewKnowledgePageSearchResponseWithDefaults instantiates a new KnowledgePageSearchResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKnowledgePageSearchResponseWithDefaults() *KnowledgePageSearchResponse {
	this := KnowledgePageSearchResponse{}
	return &this
}

// GetResults returns the Results field value
func (o *KnowledgePageSearchResponse) GetResults() []KnowledgePageSearchResult {
	if o == nil {
		var ret []KnowledgePageSearchResult
		return ret
	}

	return o.Results
}

// GetResultsOk returns a tuple with the Results field value
// and a boolean to check if the value has been set.
func (o *KnowledgePageSearchResponse) GetResultsOk() ([]KnowledgePageSearchResult, bool) {
	if o == nil {
		return nil, false
	}
	return o.Results, true
}

// SetResults sets field value
func (o *KnowledgePageSearchResponse) SetResults(v []KnowledgePageSearchResult) {
	o.Results = v
}

// GetTotal returns the Total field value
func (o *KnowledgePageSearchResponse) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *KnowledgePageSearchResponse) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *KnowledgePageSearchResponse) SetTotal(v int32) {
	o.Total = v
}

func (o KnowledgePageSearchResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KnowledgePageSearchResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["results"] = o.Results
	toSerialize["total"] = o.Total
	return toSerialize, nil
}

func (o *KnowledgePageSearchResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"results",
		"total",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKnowledgePageSearchResponse := _KnowledgePageSearchResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKnowledgePageSearchResponse)

	if err != nil {
		return err
	}

	*o = KnowledgePageSearchResponse(varKnowledgePageSearchResponse)

	return err
}

type NullableKnowledgePageSearchResponse struct {
	value *KnowledgePageSearchResponse
	isSet bool
}

func (v NullableKnowledgePageSearchResponse) Get() *KnowledgePageSearchResponse {
	return v.value
}

func (v *NullableKnowledgePageSearchResponse) Set(val *KnowledgePageSearchResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableKnowledgePageSearchResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableKnowledgePageSearchResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKnowledgePageSearchResponse(val *KnowledgePageSearchResponse) *NullableKnowledgePageSearchResponse {
	return &NullableKnowledgePageSearchResponse{value: val, isSet: true}
}

func (v NullableKnowledgePageSearchResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKnowledgePageSearchResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


