/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateKnowledgePageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateKnowledgePageResponse{}

// CreateKnowledgePageResponse Result of creating a page: the node id, its mental model, and the refresh op.
type CreateKnowledgePageResponse struct {
	PageId string `json:"page_id"`
	MentalModelId string `json:"mental_model_id"`
	OperationId NullableString `json:"operation_id,omitempty"`
}

type _CreateKnowledgePageResponse CreateKnowledgePageResponse

// NewCreateKnowledgePageResponse instantiates a new CreateKnowledgePageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateKnowledgePageResponse(pageId string, mentalModelId string) *CreateKnowledgePageResponse {
	this := CreateKnowledgePageResponse{}
	this.PageId = pageId
	this.MentalModelId = mentalModelId
	return &this
}

// NewCreateKnowledgePageResponseWithDefaults instantiates a new CreateKnowledgePageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateKnowledgePageResponseWithDefaults() *CreateKnowledgePageResponse {
	this := CreateKnowledgePageResponse{}
	return &this
}

// GetPageId returns the PageId field value
func (o *CreateKnowledgePageResponse) GetPageId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PageId
}

// GetPageIdOk returns a tuple with the PageId field value
// and a boolean to check if the value has been set.
func (o *CreateKnowledgePageResponse) GetPageIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PageId, true
}

// SetPageId sets field value
func (o *CreateKnowledgePageResponse) SetPageId(v string) {
	o.PageId = v
}

// GetMentalModelId returns the MentalModelId field value
func (o *CreateKnowledgePageResponse) GetMentalModelId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.MentalModelId
}

// GetMentalModelIdOk returns a tuple with the MentalModelId field value
// and a boolean to check if the value has been set.
func (o *CreateKnowledgePageResponse) GetMentalModelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.MentalModelId, true
}

// SetMentalModelId sets field value
func (o *CreateKnowledgePageResponse) SetMentalModelId(v string) {
	o.MentalModelId = v
}

// GetOperationId returns the OperationId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *CreateKnowledgePageResponse) GetOperationId() string {
	if o == nil || IsNil(o.OperationId.Get()) {
		var ret string
		return ret
	}
	return *o.OperationId.Get()
}

// GetOperationIdOk returns a tuple with the OperationId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CreateKnowledgePageResponse) GetOperationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.OperationId.Get(), o.OperationId.IsSet()
}

// HasOperationId returns a boolean if a field has been set.
func (o *CreateKnowledgePageResponse) HasOperationId() bool {
	if o != nil && o.OperationId.IsSet() {
		return true
	}

	return false
}

// SetOperationId gets a reference to the given NullableString and assigns it to the OperationId field.
func (o *CreateKnowledgePageResponse) SetOperationId(v string) {
	o.OperationId.Set(&v)
}
// SetOperationIdNil sets the value for OperationId to be an explicit nil
func (o *CreateKnowledgePageResponse) SetOperationIdNil() {
	o.OperationId.Set(nil)
}

// UnsetOperationId ensures that no value is present for OperationId, not even an explicit nil
func (o *CreateKnowledgePageResponse) UnsetOperationId() {
	o.OperationId.Unset()
}

func (o CreateKnowledgePageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateKnowledgePageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["page_id"] = o.PageId
	toSerialize["mental_model_id"] = o.MentalModelId
	if o.OperationId.IsSet() {
		toSerialize["operation_id"] = o.OperationId.Get()
	}
	return toSerialize, nil
}

func (o *CreateKnowledgePageResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"page_id",
		"mental_model_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateKnowledgePageResponse := _CreateKnowledgePageResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateKnowledgePageResponse)

	if err != nil {
		return err
	}

	*o = CreateKnowledgePageResponse(varCreateKnowledgePageResponse)

	return err
}

type NullableCreateKnowledgePageResponse struct {
	value *CreateKnowledgePageResponse
	isSet bool
}

func (v NullableCreateKnowledgePageResponse) Get() *CreateKnowledgePageResponse {
	return v.value
}

func (v *NullableCreateKnowledgePageResponse) Set(val *CreateKnowledgePageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateKnowledgePageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateKnowledgePageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateKnowledgePageResponse(val *CreateKnowledgePageResponse) *NullableCreateKnowledgePageResponse {
	return &NullableCreateKnowledgePageResponse{value: val, isSet: true}
}

func (v NullableCreateKnowledgePageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateKnowledgePageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


