/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the KnowledgeTreeResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KnowledgeTreeResponse{}

// KnowledgeTreeResponse The knowledge base as a nested folder/page tree.
type KnowledgeTreeResponse struct {
	Roots []KnowledgeNode `json:"roots"`
}

type _KnowledgeTreeResponse KnowledgeTreeResponse

// NewKnowledgeTreeResponse instantiates a new KnowledgeTreeResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKnowledgeTreeResponse(roots []KnowledgeNode) *KnowledgeTreeResponse {
	this := KnowledgeTreeResponse{}
	this.Roots = roots
	return &this
}

// NewKnowledgeTreeResponseWithDefaults instantiates a new KnowledgeTreeResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKnowledgeTreeResponseWithDefaults() *KnowledgeTreeResponse {
	this := KnowledgeTreeResponse{}
	return &this
}

// GetRoots returns the Roots field value
func (o *KnowledgeTreeResponse) GetRoots() []KnowledgeNode {
	if o == nil {
		var ret []KnowledgeNode
		return ret
	}

	return o.Roots
}

// GetRootsOk returns a tuple with the Roots field value
// and a boolean to check if the value has been set.
func (o *KnowledgeTreeResponse) GetRootsOk() ([]KnowledgeNode, bool) {
	if o == nil {
		return nil, false
	}
	return o.Roots, true
}

// SetRoots sets field value
func (o *KnowledgeTreeResponse) SetRoots(v []KnowledgeNode) {
	o.Roots = v
}

func (o KnowledgeTreeResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KnowledgeTreeResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["roots"] = o.Roots
	return toSerialize, nil
}

func (o *KnowledgeTreeResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"roots",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKnowledgeTreeResponse := _KnowledgeTreeResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKnowledgeTreeResponse)

	if err != nil {
		return err
	}

	*o = KnowledgeTreeResponse(varKnowledgeTreeResponse)

	return err
}

type NullableKnowledgeTreeResponse struct {
	value *KnowledgeTreeResponse
	isSet bool
}

func (v NullableKnowledgeTreeResponse) Get() *KnowledgeTreeResponse {
	return v.value
}

func (v *NullableKnowledgeTreeResponse) Set(val *KnowledgeTreeResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableKnowledgeTreeResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableKnowledgeTreeResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKnowledgeTreeResponse(val *KnowledgeTreeResponse) *NullableKnowledgeTreeResponse {
	return &NullableKnowledgeTreeResponse{value: val, isSet: true}
}

func (v NullableKnowledgeTreeResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKnowledgeTreeResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


