/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.8.3
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
)

// checks if the UpdateNodeRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateNodeRequest{}

// UpdateNodeRequest Rename, move, and/or set a folder's mission. Each field applies only when present.
type UpdateNodeRequest struct {
	Name NullableString `json:"name,omitempty"`
	ParentId NullableString `json:"parent_id,omitempty"`
	Mission NullableString `json:"mission,omitempty"`
}

// NewUpdateNodeRequest instantiates a new UpdateNodeRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateNodeRequest() *UpdateNodeRequest {
	this := UpdateNodeRequest{}
	return &this
}

// NewUpdateNodeRequestWithDefaults instantiates a new UpdateNodeRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateNodeRequestWithDefaults() *UpdateNodeRequest {
	this := UpdateNodeRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNodeRequest) GetName() string {
	if o == nil || IsNil(o.Name.Get()) {
		var ret string
		return ret
	}
	return *o.Name.Get()
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNodeRequest) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Name.Get(), o.Name.IsSet()
}

// HasName returns a boolean if a field has been set.
func (o *UpdateNodeRequest) HasName() bool {
	if o != nil && o.Name.IsSet() {
		return true
	}

	return false
}

// SetName gets a reference to the given NullableString and assigns it to the Name field.
func (o *UpdateNodeRequest) SetName(v string) {
	o.Name.Set(&v)
}
// SetNameNil sets the value for Name to be an explicit nil
func (o *UpdateNodeRequest) SetNameNil() {
	o.Name.Set(nil)
}

// UnsetName ensures that no value is present for Name, not even an explicit nil
func (o *UpdateNodeRequest) UnsetName() {
	o.Name.Unset()
}

// GetParentId returns the ParentId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNodeRequest) GetParentId() string {
	if o == nil || IsNil(o.ParentId.Get()) {
		var ret string
		return ret
	}
	return *o.ParentId.Get()
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNodeRequest) GetParentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentId.Get(), o.ParentId.IsSet()
}

// HasParentId returns a boolean if a field has been set.
func (o *UpdateNodeRequest) HasParentId() bool {
	if o != nil && o.ParentId.IsSet() {
		return true
	}

	return false
}

// SetParentId gets a reference to the given NullableString and assigns it to the ParentId field.
func (o *UpdateNodeRequest) SetParentId(v string) {
	o.ParentId.Set(&v)
}
// SetParentIdNil sets the value for ParentId to be an explicit nil
func (o *UpdateNodeRequest) SetParentIdNil() {
	o.ParentId.Set(nil)
}

// UnsetParentId ensures that no value is present for ParentId, not even an explicit nil
func (o *UpdateNodeRequest) UnsetParentId() {
	o.ParentId.Unset()
}

// GetMission returns the Mission field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *UpdateNodeRequest) GetMission() string {
	if o == nil || IsNil(o.Mission.Get()) {
		var ret string
		return ret
	}
	return *o.Mission.Get()
}

// GetMissionOk returns a tuple with the Mission field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *UpdateNodeRequest) GetMissionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Mission.Get(), o.Mission.IsSet()
}

// HasMission returns a boolean if a field has been set.
func (o *UpdateNodeRequest) HasMission() bool {
	if o != nil && o.Mission.IsSet() {
		return true
	}

	return false
}

// SetMission gets a reference to the given NullableString and assigns it to the Mission field.
func (o *UpdateNodeRequest) SetMission(v string) {
	o.Mission.Set(&v)
}
// SetMissionNil sets the value for Mission to be an explicit nil
func (o *UpdateNodeRequest) SetMissionNil() {
	o.Mission.Set(nil)
}

// UnsetMission ensures that no value is present for Mission, not even an explicit nil
func (o *UpdateNodeRequest) UnsetMission() {
	o.Mission.Unset()
}

func (o UpdateNodeRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateNodeRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Name.IsSet() {
		toSerialize["name"] = o.Name.Get()
	}
	if o.ParentId.IsSet() {
		toSerialize["parent_id"] = o.ParentId.Get()
	}
	if o.Mission.IsSet() {
		toSerialize["mission"] = o.Mission.Get()
	}
	return toSerialize, nil
}

type NullableUpdateNodeRequest struct {
	value *UpdateNodeRequest
	isSet bool
}

func (v NullableUpdateNodeRequest) Get() *UpdateNodeRequest {
	return v.value
}

func (v *NullableUpdateNodeRequest) Set(val *UpdateNodeRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateNodeRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateNodeRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateNodeRequest(val *UpdateNodeRequest) *NullableUpdateNodeRequest {
	return &NullableUpdateNodeRequest{value: val, isSet: true}
}

func (v NullableUpdateNodeRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateNodeRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


