/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.8.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the KnowledgePageBundleFile type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KnowledgePageBundleFile{}

// KnowledgePageBundleFile One file in a portable OKF bundle.
type KnowledgePageBundleFile struct {
	Path string `json:"path"`
	Content string `json:"content"`
}

type _KnowledgePageBundleFile KnowledgePageBundleFile

// NewKnowledgePageBundleFile instantiates a new KnowledgePageBundleFile object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKnowledgePageBundleFile(path string, content string) *KnowledgePageBundleFile {
	this := KnowledgePageBundleFile{}
	this.Path = path
	this.Content = content
	return &this
}

// NewKnowledgePageBundleFileWithDefaults instantiates a new KnowledgePageBundleFile object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKnowledgePageBundleFileWithDefaults() *KnowledgePageBundleFile {
	this := KnowledgePageBundleFile{}
	return &this
}

// GetPath returns the Path field value
func (o *KnowledgePageBundleFile) GetPath() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Path
}

// GetPathOk returns a tuple with the Path field value
// and a boolean to check if the value has been set.
func (o *KnowledgePageBundleFile) GetPathOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Path, true
}

// SetPath sets field value
func (o *KnowledgePageBundleFile) SetPath(v string) {
	o.Path = v
}

// GetContent returns the Content field value
func (o *KnowledgePageBundleFile) GetContent() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Content
}

// GetContentOk returns a tuple with the Content field value
// and a boolean to check if the value has been set.
func (o *KnowledgePageBundleFile) GetContentOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Content, true
}

// SetContent sets field value
func (o *KnowledgePageBundleFile) SetContent(v string) {
	o.Content = v
}

func (o KnowledgePageBundleFile) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KnowledgePageBundleFile) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["path"] = o.Path
	toSerialize["content"] = o.Content
	return toSerialize, nil
}

func (o *KnowledgePageBundleFile) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"path",
		"content",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKnowledgePageBundleFile := _KnowledgePageBundleFile{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKnowledgePageBundleFile)

	if err != nil {
		return err
	}

	*o = KnowledgePageBundleFile(varKnowledgePageBundleFile)

	return err
}

type NullableKnowledgePageBundleFile struct {
	value *KnowledgePageBundleFile
	isSet bool
}

func (v NullableKnowledgePageBundleFile) Get() *KnowledgePageBundleFile {
	return v.value
}

func (v *NullableKnowledgePageBundleFile) Set(val *KnowledgePageBundleFile) {
	v.value = val
	v.isSet = true
}

func (v NullableKnowledgePageBundleFile) IsSet() bool {
	return v.isSet
}

func (v *NullableKnowledgePageBundleFile) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKnowledgePageBundleFile(val *KnowledgePageBundleFile) *NullableKnowledgePageBundleFile {
	return &NullableKnowledgePageBundleFile{value: val, isSet: true}
}

func (v NullableKnowledgePageBundleFile) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKnowledgePageBundleFile) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


