/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.8.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the KnowledgeNode type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KnowledgeNode{}

// KnowledgeNode A node in the knowledge-base tree — a folder or a page.  Pages carry ``description``/``tags`` from their backing mental model. The knowledge base is client-managed (CRUD); ``managed`` lets a client tag a node as system-owned vs. hand-authored.
type KnowledgeNode struct {
	Id string `json:"id"`
	Kind string `json:"kind"`
	Name string `json:"name"`
	ParentId NullableString `json:"parent_id,omitempty"`
	MentalModelId NullableString `json:"mental_model_id,omitempty"`
	// Client-set flag: true = system-owned, false = hand-authored.
	Managed *bool `json:"managed,omitempty"`
	Description NullableString `json:"description,omitempty"`
	Tags []string `json:"tags,omitempty"`
	Timestamp NullableString `json:"timestamp,omitempty"`
	IsStale NullableBool `json:"is_stale,omitempty"`
	Children []KnowledgeNode `json:"children,omitempty"`
}

type _KnowledgeNode KnowledgeNode

// NewKnowledgeNode instantiates a new KnowledgeNode object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKnowledgeNode(id string, kind string, name string) *KnowledgeNode {
	this := KnowledgeNode{}
	this.Id = id
	this.Kind = kind
	this.Name = name
	var managed bool = false
	this.Managed = &managed
	return &this
}

// NewKnowledgeNodeWithDefaults instantiates a new KnowledgeNode object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKnowledgeNodeWithDefaults() *KnowledgeNode {
	this := KnowledgeNode{}
	var managed bool = false
	this.Managed = &managed
	return &this
}

// GetId returns the Id field value
func (o *KnowledgeNode) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *KnowledgeNode) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *KnowledgeNode) SetId(v string) {
	o.Id = v
}

// GetKind returns the Kind field value
func (o *KnowledgeNode) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *KnowledgeNode) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *KnowledgeNode) SetKind(v string) {
	o.Kind = v
}

// GetName returns the Name field value
func (o *KnowledgeNode) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *KnowledgeNode) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *KnowledgeNode) SetName(v string) {
	o.Name = v
}

// GetParentId returns the ParentId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KnowledgeNode) GetParentId() string {
	if o == nil || IsNil(o.ParentId.Get()) {
		var ret string
		return ret
	}
	return *o.ParentId.Get()
}

// GetParentIdOk returns a tuple with the ParentId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KnowledgeNode) GetParentIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ParentId.Get(), o.ParentId.IsSet()
}

// HasParentId returns a boolean if a field has been set.
func (o *KnowledgeNode) HasParentId() bool {
	if o != nil && o.ParentId.IsSet() {
		return true
	}

	return false
}

// SetParentId gets a reference to the given NullableString and assigns it to the ParentId field.
func (o *KnowledgeNode) SetParentId(v string) {
	o.ParentId.Set(&v)
}
// SetParentIdNil sets the value for ParentId to be an explicit nil
func (o *KnowledgeNode) SetParentIdNil() {
	o.ParentId.Set(nil)
}

// UnsetParentId ensures that no value is present for ParentId, not even an explicit nil
func (o *KnowledgeNode) UnsetParentId() {
	o.ParentId.Unset()
}

// GetMentalModelId returns the MentalModelId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KnowledgeNode) GetMentalModelId() string {
	if o == nil || IsNil(o.MentalModelId.Get()) {
		var ret string
		return ret
	}
	return *o.MentalModelId.Get()
}

// GetMentalModelIdOk returns a tuple with the MentalModelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KnowledgeNode) GetMentalModelIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.MentalModelId.Get(), o.MentalModelId.IsSet()
}

// HasMentalModelId returns a boolean if a field has been set.
func (o *KnowledgeNode) HasMentalModelId() bool {
	if o != nil && o.MentalModelId.IsSet() {
		return true
	}

	return false
}

// SetMentalModelId gets a reference to the given NullableString and assigns it to the MentalModelId field.
func (o *KnowledgeNode) SetMentalModelId(v string) {
	o.MentalModelId.Set(&v)
}
// SetMentalModelIdNil sets the value for MentalModelId to be an explicit nil
func (o *KnowledgeNode) SetMentalModelIdNil() {
	o.MentalModelId.Set(nil)
}

// UnsetMentalModelId ensures that no value is present for MentalModelId, not even an explicit nil
func (o *KnowledgeNode) UnsetMentalModelId() {
	o.MentalModelId.Unset()
}

// GetManaged returns the Managed field value if set, zero value otherwise.
func (o *KnowledgeNode) GetManaged() bool {
	if o == nil || IsNil(o.Managed) {
		var ret bool
		return ret
	}
	return *o.Managed
}

// GetManagedOk returns a tuple with the Managed field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnowledgeNode) GetManagedOk() (*bool, bool) {
	if o == nil || IsNil(o.Managed) {
		return nil, false
	}
	return o.Managed, true
}

// HasManaged returns a boolean if a field has been set.
func (o *KnowledgeNode) HasManaged() bool {
	if o != nil && !IsNil(o.Managed) {
		return true
	}

	return false
}

// SetManaged gets a reference to the given bool and assigns it to the Managed field.
func (o *KnowledgeNode) SetManaged(v bool) {
	o.Managed = &v
}

// GetDescription returns the Description field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KnowledgeNode) GetDescription() string {
	if o == nil || IsNil(o.Description.Get()) {
		var ret string
		return ret
	}
	return *o.Description.Get()
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KnowledgeNode) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Description.Get(), o.Description.IsSet()
}

// HasDescription returns a boolean if a field has been set.
func (o *KnowledgeNode) HasDescription() bool {
	if o != nil && o.Description.IsSet() {
		return true
	}

	return false
}

// SetDescription gets a reference to the given NullableString and assigns it to the Description field.
func (o *KnowledgeNode) SetDescription(v string) {
	o.Description.Set(&v)
}
// SetDescriptionNil sets the value for Description to be an explicit nil
func (o *KnowledgeNode) SetDescriptionNil() {
	o.Description.Set(nil)
}

// UnsetDescription ensures that no value is present for Description, not even an explicit nil
func (o *KnowledgeNode) UnsetDescription() {
	o.Description.Unset()
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *KnowledgeNode) GetTags() []string {
	if o == nil || IsNil(o.Tags) {
		var ret []string
		return ret
	}
	return o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnowledgeNode) GetTagsOk() ([]string, bool) {
	if o == nil || IsNil(o.Tags) {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *KnowledgeNode) HasTags() bool {
	if o != nil && !IsNil(o.Tags) {
		return true
	}

	return false
}

// SetTags gets a reference to the given []string and assigns it to the Tags field.
func (o *KnowledgeNode) SetTags(v []string) {
	o.Tags = v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KnowledgeNode) GetTimestamp() string {
	if o == nil || IsNil(o.Timestamp.Get()) {
		var ret string
		return ret
	}
	return *o.Timestamp.Get()
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KnowledgeNode) GetTimestampOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Timestamp.Get(), o.Timestamp.IsSet()
}

// HasTimestamp returns a boolean if a field has been set.
func (o *KnowledgeNode) HasTimestamp() bool {
	if o != nil && o.Timestamp.IsSet() {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given NullableString and assigns it to the Timestamp field.
func (o *KnowledgeNode) SetTimestamp(v string) {
	o.Timestamp.Set(&v)
}
// SetTimestampNil sets the value for Timestamp to be an explicit nil
func (o *KnowledgeNode) SetTimestampNil() {
	o.Timestamp.Set(nil)
}

// UnsetTimestamp ensures that no value is present for Timestamp, not even an explicit nil
func (o *KnowledgeNode) UnsetTimestamp() {
	o.Timestamp.Unset()
}

// GetIsStale returns the IsStale field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *KnowledgeNode) GetIsStale() bool {
	if o == nil || IsNil(o.IsStale.Get()) {
		var ret bool
		return ret
	}
	return *o.IsStale.Get()
}

// GetIsStaleOk returns a tuple with the IsStale field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *KnowledgeNode) GetIsStaleOk() (*bool, bool) {
	if o == nil {
		return nil, false
	}
	return o.IsStale.Get(), o.IsStale.IsSet()
}

// HasIsStale returns a boolean if a field has been set.
func (o *KnowledgeNode) HasIsStale() bool {
	if o != nil && o.IsStale.IsSet() {
		return true
	}

	return false
}

// SetIsStale gets a reference to the given NullableBool and assigns it to the IsStale field.
func (o *KnowledgeNode) SetIsStale(v bool) {
	o.IsStale.Set(&v)
}
// SetIsStaleNil sets the value for IsStale to be an explicit nil
func (o *KnowledgeNode) SetIsStaleNil() {
	o.IsStale.Set(nil)
}

// UnsetIsStale ensures that no value is present for IsStale, not even an explicit nil
func (o *KnowledgeNode) UnsetIsStale() {
	o.IsStale.Unset()
}

// GetChildren returns the Children field value if set, zero value otherwise.
func (o *KnowledgeNode) GetChildren() []KnowledgeNode {
	if o == nil || IsNil(o.Children) {
		var ret []KnowledgeNode
		return ret
	}
	return o.Children
}

// GetChildrenOk returns a tuple with the Children field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *KnowledgeNode) GetChildrenOk() ([]KnowledgeNode, bool) {
	if o == nil || IsNil(o.Children) {
		return nil, false
	}
	return o.Children, true
}

// HasChildren returns a boolean if a field has been set.
func (o *KnowledgeNode) HasChildren() bool {
	if o != nil && !IsNil(o.Children) {
		return true
	}

	return false
}

// SetChildren gets a reference to the given []KnowledgeNode and assigns it to the Children field.
func (o *KnowledgeNode) SetChildren(v []KnowledgeNode) {
	o.Children = v
}

func (o KnowledgeNode) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KnowledgeNode) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["kind"] = o.Kind
	toSerialize["name"] = o.Name
	if o.ParentId.IsSet() {
		toSerialize["parent_id"] = o.ParentId.Get()
	}
	if o.MentalModelId.IsSet() {
		toSerialize["mental_model_id"] = o.MentalModelId.Get()
	}
	if !IsNil(o.Managed) {
		toSerialize["managed"] = o.Managed
	}
	if o.Description.IsSet() {
		toSerialize["description"] = o.Description.Get()
	}
	if !IsNil(o.Tags) {
		toSerialize["tags"] = o.Tags
	}
	if o.Timestamp.IsSet() {
		toSerialize["timestamp"] = o.Timestamp.Get()
	}
	if o.IsStale.IsSet() {
		toSerialize["is_stale"] = o.IsStale.Get()
	}
	if !IsNil(o.Children) {
		toSerialize["children"] = o.Children
	}
	return toSerialize, nil
}

func (o *KnowledgeNode) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"kind",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKnowledgeNode := _KnowledgeNode{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKnowledgeNode)

	if err != nil {
		return err
	}

	*o = KnowledgeNode(varKnowledgeNode)

	return err
}

type NullableKnowledgeNode struct {
	value *KnowledgeNode
	isSet bool
}

func (v NullableKnowledgeNode) Get() *KnowledgeNode {
	return v.value
}

func (v *NullableKnowledgeNode) Set(val *KnowledgeNode) {
	v.value = val
	v.isSet = true
}

func (v NullableKnowledgeNode) IsSet() bool {
	return v.isSet
}

func (v *NullableKnowledgeNode) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKnowledgeNode(val *KnowledgeNode) *NullableKnowledgeNode {
	return &NullableKnowledgeNode{value: val, isSet: true}
}

func (v NullableKnowledgeNode) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKnowledgeNode) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


