/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.8.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the KnowledgePageBundleResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &KnowledgePageBundleResponse{}

// KnowledgePageBundleResponse A portable OKF bundle — a flat set of markdown files (index + pages + logs).
type KnowledgePageBundleResponse struct {
	Files []KnowledgePageBundleFile `json:"files"`
}

type _KnowledgePageBundleResponse KnowledgePageBundleResponse

// NewKnowledgePageBundleResponse instantiates a new KnowledgePageBundleResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewKnowledgePageBundleResponse(files []KnowledgePageBundleFile) *KnowledgePageBundleResponse {
	this := KnowledgePageBundleResponse{}
	this.Files = files
	return &this
}

// NewKnowledgePageBundleResponseWithDefaults instantiates a new KnowledgePageBundleResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewKnowledgePageBundleResponseWithDefaults() *KnowledgePageBundleResponse {
	this := KnowledgePageBundleResponse{}
	return &this
}

// GetFiles returns the Files field value
func (o *KnowledgePageBundleResponse) GetFiles() []KnowledgePageBundleFile {
	if o == nil {
		var ret []KnowledgePageBundleFile
		return ret
	}

	return o.Files
}

// GetFilesOk returns a tuple with the Files field value
// and a boolean to check if the value has been set.
func (o *KnowledgePageBundleResponse) GetFilesOk() ([]KnowledgePageBundleFile, bool) {
	if o == nil {
		return nil, false
	}
	return o.Files, true
}

// SetFiles sets field value
func (o *KnowledgePageBundleResponse) SetFiles(v []KnowledgePageBundleFile) {
	o.Files = v
}

func (o KnowledgePageBundleResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o KnowledgePageBundleResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["files"] = o.Files
	return toSerialize, nil
}

func (o *KnowledgePageBundleResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"files",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varKnowledgePageBundleResponse := _KnowledgePageBundleResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varKnowledgePageBundleResponse)

	if err != nil {
		return err
	}

	*o = KnowledgePageBundleResponse(varKnowledgePageBundleResponse)

	return err
}

type NullableKnowledgePageBundleResponse struct {
	value *KnowledgePageBundleResponse
	isSet bool
}

func (v NullableKnowledgePageBundleResponse) Get() *KnowledgePageBundleResponse {
	return v.value
}

func (v *NullableKnowledgePageBundleResponse) Set(val *KnowledgePageBundleResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableKnowledgePageBundleResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableKnowledgePageBundleResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableKnowledgePageBundleResponse(val *KnowledgePageBundleResponse) *NullableKnowledgePageBundleResponse {
	return &NullableKnowledgePageBundleResponse{value: val, isSet: true}
}

func (v NullableKnowledgePageBundleResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableKnowledgePageBundleResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


